### ISSUE TITLE
How to mount XFS?

### ISSUE THREAD

**Issue by cathaysia** [crossmeta/cxfuse#12]
I had installed  crossmeta-fuse-2_0_3 and relogin. My explorer have V volume.
But when I try _mount -t xfs /dev/da1s3 /home_, it looks nothing happend. And /home is empty still.

Do you can help mount xfs on windows10 64 bits?

**Comment by crossmeta** [comment]
Hello,

Can you check the driver messages by running dmesg.exe that is part of
crossmeta.

Maybe XFS superblock has some new features enabled that is not supported by
this xfs driver.

Always  try to mount read-only

 *mount -r -t xfs /dev/da1s3 /mnt*


*Best regards*

**Comment by cathaysia** [comment]
There are all the message of cmd:

```cmd
V:\>ls
bin         dev         home        lib64       mnt         root        tmp         var
cachefs     etc         lib         lost+found  proc        sbin        usr

V:\>ls /dev
da0    da0s1  da0s2  da1    da1s1  da1s2  da1s3  da1s4  da1s5  da1s6  da1s7  loop   loop0  null   zero

V:\>mount -r -t xfs /dev/da1s3 /mnt*
mount: /mnt*

V:\>dmesg.exe

Crossmeta Solutions Crossmeta 2.0.2-RELEASE #240: Mon Apr  8 18:17:44 PDT 2019
    bldmaster@buildhost.crossmeta.org:/build/release_2_0/crossmeta/sys/kern
Copyright (c) 2008-2011 Crossmeta Org.
Copyright (c) 2000 Sammandam, Supramani.
Copyright (c) 1989, 1991, 1993
The Regents of the University of California.  All rights reserved.

zero: major 2 minor 0xc
null: major 2 minor 0x2
da0: major 3 minor 0x10002
da0s1: major 3 minor 0x20002
da0s2: major 3 minor 0x30002
da1: major 3 minor 0x1000a
da1s1: major 3 minor 0x2000a
da1s2: major 3 minor 0x3000a
da1s3: major 3 minor 0x4000a
da1s4: major 3 minor 0x5000a
da1s5: major 3 minor 0x6000a
da1s6: major 3 minor 0x7000a
da1s7: major 3 minor 0x8000a
loop: major 7 minor 0xff
loop0: major 7 minor 0x0
loop0: added \DosDevices\C:\Program Files\crossmeta\rootfs.img size 0 bytes
vfsroot on /dev/loop0, fstype ufs
kern_authmap: flush old mappings
VFS: Received PnP request code 0x7
VFS: PnP Not our device object FFFF9F09AE859E00
VFS: Received PnP request code 0x7
VFS: PnP Not our device object FFFF9F09AE859E00
VFS: Received PnP request code 0x7
VFS: PnP Not our device object FFFF9F09AE859E00
VFS: Received PnP request code 0x7
VFS: PnP Not our device object FFFF9F09AE859E00
getdirents: directory entry .. ignored
XFS: with log version 2 support loaded
```

**Comment by crossmeta** [comment]
The mount point should be a folder that already exists.  Note sure why
/mnt* was sure. It should be just /mnt

Also as mentioned here XFS SB version 5 is not supported
https://github.com/crossmeta/sgi/issues/1

**Comment by cathaysia** [comment]
OK, maybe my xfs is XFS SB version 5. Because my linux is Manjaro. The /dev had been empty after I reboot win10. Though I start all service of crossmeta.

I create a floder at root path and mount it at first. But it fail still.

**Comment by crossmeta** [comment]
Maybe devfs /dev was not mounted, which can be fixed
v:\> mount -a

If /dev was empty then mount cannot work since it needs device name.

If root file system needs to be repaired and remounted
c:\> cd "program files\crossmeta"
c:> service_crossmeta start
c:> service_crossmeta check

c:\> net start xfs
mount -r -t xfs /dev/da1s3. /mnt

Check dmesg output for clues
v:>dmesg.exe

Best,
